apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: homelab-backstage
  namespace: argocd
spec:
  # Argo CD Applications live here
  namespace: argocd

  # Application write-back (no Git commits)
  writeBackConfig:
    method: argocd

  applicationRefs:
    - namePattern: "homelab-backstage"
      images:
        - alias: backstage

          # Harbor project repo (avoid library/)
          imageName: harbor.maksonlee.com/backstage/homelab-backstage:test

          commonUpdateSettings:
            updateStrategy: digest

          # Must match the image identifier used in your manifests (without tag)
          manifestTargets:
            kustomize:
              name: harbor.maksonlee.com/backstage/homelab-backstage
